{if $DO == 'new'}
<h4>Autorizzazione al trattamento dei dati</h4> 
	
	<div class="ml_open">
		<p><textarea rows="5" readonly="readonly" cols="65"> Gentile utente, nel rispetto di quanto previsto dal Decreto legislativo n. 196 del 30 giugno 2003 ("Codice in materia di protezione dei dati personali") a tutela del trattamento dei dati personali, Le confermiamo che detto trattamento sar&agrave; improntato ai principi di correttezza, liceit&agrave; e trasparenza e di tutela della Sua riservatezza e dei Suoi diritti.
Ai sensi dell'articolo 13 del D.lgs. n.196/2003, pertanto, Le forniamo le seguenti informazioni:
- La raccolta e il trattamento dei dati personali ha la finalit&agrave; di inviare la Newsletter  all'indirizzo di posta elettronica fornito. La Newsletter potr&agrave; contenere informazioni, proposte commerciali. Inoltre potranno essere trattati a scopo di ricerca e comunque sempre senza entrare nella sfera dei dati sensibili.
- Il trattamento sar&agrave; effettuato con modalit&agrave; informatizzate.
- Il conferimento dei dati contraddistinti con asterisco (*) &egrave; obbligatorio per accedere all'iscrizione, mentre gli altri dati sono facoltativi e l'eventuale rifiuto di fornire tali dati non ha alcuna conseguenza.
- I dati non saranno comunicati ad altri soggetti, n&egrave; saranno oggetto di diffusione.
- L'interessato ha facolt&agrave; di acquisire informazioni in merito al trattamento dei propri dati e/o di intervenire sul loro trattamento secondo i diritti e le modalit&agrave; di accesso previsti dall'art.7 D.lgs.196/2003, che riproduciamo integralmente:Decreto Legislativo n.196/2003, Art. 7 - Diritto di accesso ai dati personali ed altri diritti.1. L'interessato ha diritto di ottenere la conferma dell'esistenza o meno di dati personali che lo riguardano, anche se non ancora registrati, e la loro comunicazione in forma intelligibile.2. L'interessato ha diritto di ottenere l'indicazione:  a) dell'origine dei dati personali;  b) delle finalit&agrave; e modalit&agrave; del trattamento;  c) della logica applicata in caso di trattamento effettuato con l'ausilio di strumenti elettronici;  d) degli estremi identificativi del titolare, dei responsabili e del rappresentante designato ai sensi dell'articolo 5, comma 2;  e) dei soggetti o delle categorie di soggetti ai quali i dati personali possono essere comunicati o che possono venirne a conoscenza in qualit&agrave; di rappresentante designato nel territorio dello Stato, di responsabili o incaricati. 3. L'interessato ha diritto di ottenere:  a) l'aggiornamento, la rettificazione ovvero, quando vi ha interesse, l'integrazione dei dati;  b) la cancellazione, la trasformazione in forma anonima o il blocco dei dati trattati in violazione di legge, compresi quelli di cui non &egrave; necessaria la conservazione in relazione agli scopi per i quali i dati sono stati raccolti o successivamente trattati;  c) l'attestazione che le operazioni di cui alle lettere a) e b) sono state portate a conoscenza, anche per quanto riguarda il loro contenuto, di coloro ai quali i dati sono stati comunicati o diffusi, eccettuato il caso in cui tale adempimento si rivela impossibile o comporta un impiego di mezzi manifestamente sproporzionato rispetto al diritto tutelato.4. L'interessato ha diritto di opporsi, in tutto o in parte:  a) per motivi legittimi al trattamento dei dati personali che lo riguardano, ancorch&egrave; pertinenti allo scopo della raccolta;  b) al trattamento di dati personali che lo riguardano a fini di invio di materiale pubblicitario o di vendita diretta o per il compimento di ricerche di mercato o di comunicazione commerciale.  </textarea>
		<br />Autorizzo il trattamento dei miei dati personali ai sensi del Decreto legislativo n. 196/2003.<br /><br />
		<input type="radio" name="user[terms]" value="1" {$terms_checked_yes}/><label for="accept">{tz}terms_yes{/tz}</label>
		&nbsp;
		<input type="radio" name="user[terms]" value="0" {$terms_checked_no}/><label for="dont_accept">{tz}terms_no{/tz}</label>
		</p>
	</div>
{/if}